[project]
name = "dcs_computations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"  

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "ty>=0.0.63",
    "maturin>=1.14.1",
    "ruff>=0.15.22",
    "mypy>=2.3.0",
]
